### ISSUE TITLE
bunyan-log4stuff

### ISSUE THREAD

**Issue by akreienbring** [ytechie/winston-log4stuff#1]
Hello,
as I had trouble using winston (getting 'callback already called' errors) I swiched to bunyard.
By looking at your log4Stuff integration with winston I wrote a module that I called "log4StuffStream" for this alternative node.js logging framework.

Are you interested in maintaining the code as you do for winston?

**Comment by ytechie** [comment]
Do you have a link to bunyard? I haven't heard of that. If it's popular, I don't mind maintaining it.

**Comment by akreienbring** [comment]
Ooops, I misspelled the name. It's bunyan.

Look here: https://github.com/trentm/node-bunyan
and here: http://strongloop.com/strongblog/compare-node-js-logging-winston-bunyan/

**Comment by ytechie** [comment]
Sure, whatever you want to do. Feel free to put it on GitHub, or send it my way and I will.

**Comment by akreienbring** [comment]
This is the code of the node module. Sorry for sending it like this, but I forking your repo for this makes no sense.

```
var http = require('http');

var BunyardLog4Stuff = function(appId){
    //a little helper to make the time more pretty
    Number.prototype.pad = function (len) {
        return (new Array(len+1).join("0") + this).slice(-len);
    };

    return {
        write: function(obj, encoding) {

            var levelFromNumber = {
                '10': 'trace',
                '20': 'debug',
                '30': 'info',
                '40': 'warn',
                '50': 'error',
                '60': 'fatal'
            };

            var meta = {};
            meta["log4net:HostName"] = obj.hostname;

            var now = new Date();
            var dateStr = now.getFullYear() + "-"
                + (1 + now.getMonth()) + "-"
                + now.getDate() + " "
                + now.getHours().pad(2) + ":"
                + now.getMinutes().pad(2) + ":"
                + now.getSeconds().pad(2);


            var logEvent = {
                "Logger": "bunyan",
                "Thread": "",
                "Timestamp": dateStr,
                "Level": levelFromNumber[obj.level],
                "Message": obj.msg,
                "Metadata": meta
            };

            var json = JSON.stringify(logEvent);
            var encoded = escape(json);
            var url = "http://log4stuff.com/app/" + appId + "?logEvent=" + encoded;

            var request = http.get(url, function(res) {
                if(res.statusCode == 200) {
                    //do nothing
                } else {
                    //Remote server error
                };
            }).on('error', function(err) {
                //without listing to this event an ECONNRESET error is thrown
            });
            request.shouldKeepAlive = false;
        }
    };
};

module.exports = BunyardLog4Stuff;
```

And this is how it can be used:

```
var Bunyan = require('bunyan');
var BunyardLog4Stuff = require('./log4StuffStream');
var bunyardLog4Stuff = new BunyardLog4Stuff("<appId>");

var Logger = Bunyan.createLogger({
    name: 'someName',
    streams: [
        {
            level: 'info',
            type: "raw",
            stream: bunyardLog4Stuff
        }
    ],
    serializers: {
        err: Bunyan.stdSerializers.err,
        req: Bunyan.stdSerializers.req,
        res: Bunyan.stdSerializers.res,
    }
})
```

BTW: I always see this ECONNRESET error thrown when http.get's your service. It seems that the Log4Stuff server terminates the connection without sending a valid response. Maybe you can have a look into that.

And I would suppose to rename you repo to something like "Log4Stuff Appenders" and collect different appenders to your great service here.

**Comment by ytechie** [comment]
A work in progress. Watch there for updates:
https://github.com/ytechie/bunyan-log4stuff

I'm troubleshooting the 200 error you mentioned. Log4stuff should definitely return a valid response.

I'm thinking about open sourcing that whole site... nothing too proprietary there.
